services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: framezzz-api/Dockerfile
    image: api:go
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    ports:
      - '7312:7312'
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: framezzz-frontend/Dockerfile
    ports:
      - '4200:4200'
    environment:
      - NODE_ENV=development

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: framezzz-auth/Dockerfile
    image: auth:go
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    ports:
      - '7313:7313'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
