definitions:
  model.GetComicResponse:
    properties:
      coverUrl:
        type: string
      id:
        type: integer
      postUrl:
        type: string
      title:
        type: string
    type: object
  model.IDResponse:
    properties:
      id:
        type: integer
    type: object
info:
  contact: {}
  description: Api Endpoints for Go Server
  title: Go Rest Api
paths:
  /api/comic/{id}:
    get:
      parameters:
      - description: Comic ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetComicResponse'
      summary: Get a specific comic
      tags:
      - Comics
  /api/comic/update:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Comic title
        in: body
        name: title
        schema:
          type: string
      - description: Comic coverUrl
        in: body
        name: coverUrl
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.IDResponse'
      summary: Update a specific Comic
      tags:
      - Comics
  /api/comics:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.GetComicResponse'
            type: array
      summary: Get all comics
      tags:
      - Comics
swagger: "2.0"
